### ISSUE TITLE
"SETUP.TRA" (newer) VS "setup.tra" (older)

### ISSUE THREAD

**Issue by Frenzgyn** [Skitia/Nalia_At_Last#1]
Hi!

"Casesensitiveness" bug with the leftover older english "setup.tra" (all lowercase) which lacks the last line: 
`
 "@10 = ~Lord De'Arnise~"`
 
 By default while you decompress the archive it ask to overwrite the newest with lowest, so it might create some bugs if the user don't pay attention.

**Comment by Skitia** [comment]
Thanks, this is fixed.
